
#List of curio slot type settings
[[curiosSettings]]
	identifier = "curio"
	size = 6
	override = false

[[curiosSettings]]
	identifier = "head"
	size = 2
	override = false

[[curiosSettings]]
	identifier = "necklace"
	size = 2
	override = false

[[curiosSettings]]
	identifier = "back"
	size = 2
	override = false

[[curiosSettings]]
	identifier = "body"
	size = 2
	override = false

[[curiosSettings]]
	identifier = "bracelet"
	size = 2
	override = false

[[curiosSettings]]
	identifier = "hands"
	size = 2
	override = false

[[curiosSettings]]
	identifier = "ring"
	size = 4
	override = false

[[curiosSettings]]
	identifier = "belt"
	size = 2
	override = false

[[curiosSettings]]
	identifier = "charm"
	size = 2
	override = false

[[curiosSettings]]
	identifier = "feet"
	size = 2
	override = false
