
[general]
	fasciatedDandelionDropsNormalDandelionWhenUsingBoneMeal = true
	fasciatedOxeyeDaisyDropsNormalOxeyeDaisyWhenUsingBoneMeal = true
	#Range: 0.0 ~ 1.0
	dandelionFasciationChance = 0.4
	#Range: 0.0 ~ 1.0
	oxeyeDaisyFasciationChance = 0.4
	additionalChestLoots = true
	additionalWandererTrades = true

