
[blacklist]
	#List of the mods you want to blacklist
	#Example: ["perpetual", "botania"]
	#default: []
	mods = []
	#List of the item IDs you want to blacklist
	#Example: ["minecraft:shield", "minecraft:diamond_sword"]
	#default: []
	items = []
	#List of the item tags you want to blacklist
	#Example: ["forge:tools/shovel"]
	#default: []
	tags = []

